# Generated by Django 6.0 on 2025-12-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('occupation', models.CharField(choices=[('Branch Leader', 'Branch Leader'), ('A-Team', 'A-Team'), ('Z-Team', 'Z-Team')], max_length=50)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('power', models.CharField(max_length=200)),
                ('image_filename', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
